import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: process.env.HOME + '/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome' });
const p = await b.newPage({ viewport: { width: 1600, height: 950 } });
await p.goto('http://localhost:4680');
await p.waitForTimeout(2000);
await p.getByRole('button', { name: /역할/ }).click();
await p.waitForTimeout(600);
await p.screenshot({ path: '/tmp/claude-1001/-home-geondev/b4e5ebf5-d25a-4a0c-a18a-436238ca1a34/scratchpad/gp-roles.png' });
await b.close();
console.log('OK');
